### ISSUE TITLE
RestDB functionality causes resolver to explode with mismatch number of parameters

### ISSUE THREAD

**Issue by jm650** [smck83/expurgate#4]
I believe the issue is that the function restdb is defined for three parameters:
def restdb(restdb_url,restdb_key,mydomains):

However the function is called with two parameters on line 101:
restdbdomains = restdb(restdb_url,restdb_key)

Which results in the following error:

```
Traceback (most recent call last):
 File "/opt/expurgate/resolver.py", line 101, in <module>
  restdbdomains = restdb(restdb_url,restdb_key)
TypeError: restdb() missing 1 required positional argument: 'mydomains'
Traceback (most recent call last):
 File "/opt/expurgate/resolver.py", line 101, in <module>
  restdbdomains = restdb(restdb_url,restdb_key)
TypeError: restdb() missing 1 required positional argument: 'mydomains'
Traceback (most recent call last):
 File "/opt/expurgate/resolver.py", line 101, in <module>
  restdbdomains = restdb(restdb_url,restdb_key)
TypeError: restdb() missing 1 required positional argument: 'mydomains'
Traceback (most recent call last):
 File "/opt/expurgate/resolver.py", line 101, in <module>
  restdbdomains = restdb(restdb_url,restdb_key)
TypeError: restdb() missing 1 required positional argument: 'mydomains'

```

**Comment by smck83** [comment]
Thanks for reporting. I will investigate, test and resolve shortly

**Comment by smck83** [comment]
It appears this issue should be logged against https://github.com/smck83/expurgate-solo/ rather than https://github.com/smck83/expurgate/

i.e. /expurgate-resolver/ under /expurgate/ already only requires 2 variables

https://github.com/smck83/expurgate/blob/main/expurgate-resolver/resolver.py

````
def restdb(restdb_url,restdb_key):
    payload={}
    headers = {
````

I have made changes to https://github.com/smck83/expurgate-solo/blob/main/config/resolver.py and removes the mydomains variable in the definition which is not required as it is a global variable.
